### ISSUE TITLE
ValueError: DataFrame.dtypes for data must be int, float or bool.

### ISSUE THREAD

**Issue by ChuliangXiao** [snowflakedb/snowflake-ml-python#41] opened 2023-09-05 19:50 UTC
Try to use `LGBMClassifier`
```python
from snowflake.ml.modeling.lightgbm import LGBMClassifier

clf = LGBMClassifier(
    input_cols=INPUT_COLUMS,
    label_cols=LABEL_COLUMN,
    output_cols=OUTPUT_COLUMN,
    **params
)
clf.fit(train_df)

result = clf.predict(test_df)

result.groupBy(OUTPUT_COLUMN).count().show()
```
and got the following error
```
raise ValueError("DataFrame.dtypes for data must be int, float or bool.\n"
ValueError: DataFrame.dtypes for data must be int, float or bool.
Did not expect the data types in the following fields: ... some fields...
```
while all those fields are `DoubleType()` or `LongType()`. Still got the same issue after `.cast(FloatType())`.

**Comment by sfc-gh-xjiang** [comment] 2023-09-12 21:52
Hi @ChuliangXiao, this error may come from LightGBM model itself. Would you mind looking at solutions like [this](https://stackoverflow.com/questions/64524749/lightgbm-valueerror-series-dtypes-must-be-int-float-or-bool)  or [this](https://stackoverflow.com/questions/64333930/lightgbm-does-not-accept-the-dtypes-of-my-data)? If they don't work for you, could you provide any more details for your problem, such as the schema of your table - which would be easier for me to reproduce your error?

**Comment by ChuliangXiao** [comment] 2023-09-12 22:51
> Hi @ChuliangXiao, this error may come from LightGBM model itself. Would you mind looking at solutions like [this](https://stackoverflow.com/questions/64524749/lightgbm-valueerror-series-dtypes-must-be-int-float-or-bool) or [this](https://stackoverflow.com/questions/64333930/lightgbm-does-not-accept-the-dtypes-of-my-data)? If they don't work for you, could you provide any more details for your problem, such as the schema of your table - which would be easier for me to reproduce your error?

Had the same issue with XGBoost.
It's fine while manually creating a stored procedure in which Snowflake DF is converted `.toPandas()` to Pandas DF

**Comment by sfc-gh-xjiang** [comment] 2023-12-06 20:22
Hey @ChuliangXiao , how is everything going? I want to follow up the issue and see if you can provide a dataset/table schema so that I can reproduce the issue. If the problem is solved, I can close this issue.

**Comment by sfc-gh-wzhao** [comment] 2024-03-28 20:55
Hi @ChuliangXiao , we are closing this stale issue. If you have any updates, please re-open it. Thank you for supporting.

**Closed by sfc-gh-wzhao** 2024-03-28 20:55 UTC
Labels: bug
